name: null

channels:
  - conda-forge
  - nodefaults

dependencies:
  - jupyterlab
  - jupyterlab-lsp
  - numpy
  - openai
  - pip
  - pip:
    - -r requirements.txt
  - python
  - python-lsp-server
  - tqdm
